services:
  db:
    image: postgres:15-alpine
    container_name: moodproject_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-mood_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-mood_db}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mood_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moodproject_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-mood_db}?schema=public
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-supersecretmockkey}
      GIPHY_API_KEY: ${GIPHY_API_KEY}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      AUTH_TRUST_HOST: "true"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mood_network

networks:
  mood_network:
    driver: bridge

volumes:
  postgres_data:
